import React from 'react'
import { useState } from 'react'
import "./item.css"
function Items() {
    const [copy, setcopy] = useState("Here you can see the procedure to make")
    const [item, setitem] = useState([
        { image: "https://i.ytimg.com/vi/4kEQ21ZMQPE/maxresdefault.jpg", name: "Rasgulla", content: "Take 1 litre of whole milk in a pan and bring it to a low boil on a low to medium heat. While the milk is heating up, line a mesh strainer or colander with a piece of cheese cloth or muslin. Keep stirring the milk at intervals. This will help to prevent froth from forming on top and the base from scorching. When the milk comes to a boil, then reduce the heat to its lowest. Add 1 to 3 tablespoons of lemon juice. Start with just 1 tablespoon of lemon juice and stir very well. If the milk has not curdled completely, then add more. Keep the lemon juice handy so you can add it as needed. As soon as the milk curdles, switch off the heat. The milk should curdle completely and you should see a green watery whey. Now pour the curdled milk in the cheese cloth/muslin lined strainer or bowl. Gather the muslin from the sides and rinse the chenna or coagulated milk solids very well in running water. This brings down the temperature of chenna as well as removes the lemony flavor and tangy taste from the chenna. Now squeeze the muslin with your hands very well so that excess water is drained from the chenna. Place a heavy weight on the chenna for 7 to 8 minutes, or hang it for about 30 minutes. After the chenna is thoroughly drained, remove the cheesecloth. Think of chenna like Goldilocks it should not have too much moisture nor be too dry. The texture below is just right! Add 1 teaspoon unroasted sooji, rava or semolina. The rava I had was coarse, but a finer one will also work well. First mix the sooji with chenna and then begin to knead. With the heels of your palms, mash the chenna and knead. Keep on collecting the chenna from the sides and continue to mash and knead. Knead to a smooth ball of chenna which should be able to come together without breaking or falling apart. A close up photo showing you the texture of the chenna dough. Now pinch small portions from the chenna and roll them between your palms to a smooth round ball. Make Sugar Syrup  In a large pot, take 2 cups sugar. Add 4 cups water (1 litre). Be sure to use a large pot or pan so that there is enough space for the rasgulla to cook and increase in size. You can also use a stovetop pressure cooker.  Heat the sugar solution on the stovetop over medium heat, stirring so the sugar dissolves. You dont need to boil the solution. Once the sugar solution becomes hot, the impurities begin to flot on the top. Once all the rasgulla have been added to the sugar solution, gently shake the pot. Dont stir the rasgulla with a spoon. After 4 minutes, again add ¼ cup of the reserved sugar solution. Cover and again cook for 2 minutes. In total, the rasgulla balls cooked for about 10 minutes. After 10 minutes, they had increased in size and were done." },
        { image: "https://www.cookwithmanali.com/wp-content/uploads/2014/07/Rasmalai-Recipe.jpg", name: "Rasmalai", content: "Firstly, in a thick bottomed pan add 1 litre cows milk. make sure to use cows milk, else rasmalai will not be soft and juicy. furthermore, stir occasionally and get to a boil. additionally, add lemon juice and stir well. add more lemon juice and stir till milk curdles completely. and immediately drain the curdled milk into the hand kerchief / cheese cloth. pour a cup of water and clean the paneer as it has lemon juice in it. furthermore, bring it together and squeeze off excess water. hang for 30 minutes. or till all the water drains off completely. after 30 minutes, start to knead the paneer for 10 minutes. knead paneer till it turns out smooth without any grains of milk. else there will be cracks on rasmalai and will break while boiling in sugar syrup. furthermore, make small balls and flatten. keep aside. firstly, in a deep vessel take 1½ cup of sugar. furthermore, add 8 glasses of water and stir well. boil the syrup for 10 minutes on medium flame. after that, drop the prepared flattened paneer balls into boiling sugar syrup. cover and boil for 15 minutes. the flattened paneer balls will have doubled in size. furthermore, with a help of slotted spoon take each rasmalai and squeeze of sugar syrup. allow all the squeezed paneer balls to cool completely. or till they come to room temperature. firstly, in a large nonstick pan heat milk. furthermore, stir occasionally and get to a boil. reduce the flame to medium. and once a layer of cream is formed over the milk, stick it to sides of vessel. further, get the milk to boil again. and repeat the gathering of cream to sides of kadai. repeat the process for atleast 5 times or till milk reduces to one-third. give a good mix and get the milk again to boil. also scrape off the collected cream from sides. and give a good stir. transfer to a bowl and let it attain to room temperature. further, refrigerate for 2-3 hours before adding to rasmalai. firstly, generously pour the chilled rabri / rabdi over the squeezed paneer balls. also garnish with few chopped nuts and allow to absorb for 2 hours. Finally, rasmalai is ready to be served. " },
        { image: "https://3.imimg.com/data3/MA/AP/MY-14227798/neetu-500x500.png", name: "Gulabjamun", content: " Take 1 cup khoya or mawa (200 grams) in a bowl. Soft khoya also known as daap ka khoya or chikna khoya is used. This is a soft khoya, so it mashes and kneads very well. Mash it very well. There should be no lumps or small bits or pieces in the khoya. You can also grate and then mash the khoya. Do not mash too much. Just mash and proceed with the next step. Then add ¾ cup or 100 grams grated paneer, fine rava (semolina), 2 tablespoons all-purpose flour, ¼ teaspoon baking powder and ½ teaspoon cardamom powder to the mashed khoya. There should be no lumps in both the mawa and paneer. If there are lumps, then the texture is not even and smooth. The bits and pieces of mawa or paneer give a bite while eating. Mix well. Add 1 tablespoon milk and gather together to form a dough with milk. Don’t knead. Just gently mix. If you are unable to form balls or if the mixture appears dry, then add a few teaspoons of milk and mix again. Cover the dough and set aside for 30 minutes. Mix 1.75 cups (250 grams) sugar in 1 cup water. On a medium-low flame, heat the sugar solution till it becomes sticky. You just need to switch off the fire before the syrup reaches a one thread consistency. I have used raw sugar which made the syrup have a dark color. The syrup should be sticky and not watery. You can even cook the sugar syrup till it reaches a half-string consistency. Add rose water and stir. Set the sugar solution aside. On cooling, if the sugar syrup crystallizes, then just add 2 to 3 tablespoons water and warm the syrup again. Stir while warming the syrup. The sugar crystals will disappear. After 30 minutes, make small balls from the dough without cracks. Cover the dough balls and set aside. Heat oil until it is medium-hot. Lower the flame to a medium-low or low and wait for a minute. Then gently place the dough balls in the oil. If in case, the dough balls breaks when frying, then add some more maida (about 1 to 2 tablespoons) to the dough. Mix gently again. Set aside for fifteen minutes. Then later fry. You can also check one small piece before frying the rest of the balls. If it breaks, then use the tip mentioned above. Once they start to have tiny golden spots, keep on rotating them in the oil, so that the balls are evenly browned. Since I was taking the photos, I browned a few of them more.  Remove the fried dough balls and then place them on kitchen paper towels to remove extra oil. Place the hot fried dough balls in the sugar syrup. Continue to fry the rest of the dough balls in batches. Later place them while still hot in the sugar syrup. Dont overcook as then they can break. Use a large pan, so that the fried jamun balls are not overcrowded and you can easily stir them gently while they are simmering. Serve gulab jamun warm or at room temperature. You can also chill them and serve them cold. Garnish them with rose petals or almond slivers." }])
    let Display = (id) => {
        let a = item[id]
        setcopy(a.content)
    }
    return (
        <div className='container-fluid'>
            <div className='row'>
                <div className='col-2' >
                    {
                        item.map((val, idx) => {
                            return <div onClick={() => { Display(idx) }} className='card bg-secondary'><img className='card-img-top' src={val.image} key={idx} />
                                <div className='card-body'>
                                    <h4 className='card-title'>{val.name}</h4>
                                </div>
                            </div>
                        })
                    }
                </div>
                <div className='col-10'>
                    <h5>{copy}</h5>
                </div>
            </div>
        </div>
    )
}

export default Items
